"""Editorial reference, not a classifier or a set of mandatory plot rules."""
GENRES = [
    ("Drame", "L’expérience humaine et les conséquences émotionnelles des choix sont au premier plan. Le conflit peut être intime, familial, professionnel ou social : son importance vient de ce qu’il transforme, pas de son ampleur spectaculaire.",
     "Relations évolutives, désirs contradictoires, décisions coûteuses, attention aux gestes et aux silences. Une fin heureuse est possible : drame ne signifie pas nécessairement tragédie.",
     "Le mélodrame amplifie les émotions et les oppositions morales ; la tragédie organise une perte irréversible. Un drame peut aussi être comique, historique ou fantastique."),
    ("Comédie", "Le plaisir principal vient du décalage entre attentes, comportements et résultats. Le rire peut naître d’un caractère, d’une situation, du langage, du rythme ou d’une critique sociale.",
     "Préparation et surprise, escalade, répétition avec variation, contraste entre ce qu’un personnage veut montrer et ce qu’il révèle. Les personnages ont besoin d’enjeux sincères même si leurs méthodes sont absurdes.",
     "La satire vise des comportements ou institutions ; la parodie transforme les codes d’une œuvre ou d’un genre ; la comédie noire tire son humour de situations graves. Le ton ne détermine pas la structure."),
    ("Romance", "La formation, l’épreuve ou la reconstruction d’un lien amoureux constitue le moteur central. La question n’est pas seulement de réunir deux personnes, mais de comprendre ce qui leur permet ou leur interdit d’aimer.",
     "Attirance crédible, besoins incompatibles, vulnérabilité, limites et choix réciproques. La relation évolue à travers les actes, pas uniquement à travers des déclarations.",
     "Une intrigue amoureuse secondaire ne transforme pas automatiquement un récit en romance. La romance commerciale promet souvent une résolution heureuse ou porteuse d’espoir ; une histoire d’amour tragique peut volontairement choisir une autre promesse."),
    ("Policier / enquête", "La recherche d’une vérité organise le récit : qui a agi, comment, pourquoi ? L’enquête peut appartenir à un professionnel, à un témoin ou à une personne impliquée malgré elle.",
     "Indices interprétables, hypothèses, contradictions, fausses pistes motivées et révélations qui changent la lecture des faits. Répartir l’information entre enquêteur, suspects et lecteur est essentiel.",
     "Le mystère privilégie la découverte ; le procedural détaille le travail d’enquête ; le noir insiste sur la corruption et les compromis. Le thriller privilégie davantage le danger imminent."),
    ("Thriller / suspense", "L’anticipation d’une menace entretient la tension. Le public peut connaître un danger ignoré du protagoniste, ou partager son incertitude ; l’essentiel est ce qui risque d’arriver.",
     "Pression temporelle, options qui se ferment, information incomplète, retournements préparés et décisions risquées. Alterner tension et relâchement évite de rendre tous les instants équivalents.",
     "Le thriller psychologique joue sur la perception et les rapports de pouvoir ; le thriller politique sur les institutions ; le techno-thriller sur les systèmes techniques. Suspense et violence ne sont pas synonymes."),
    ("Horreur", "La peur, l’effroi, le dégoût ou l’inquiétante étrangeté sont des expériences centrales. La menace met en crise le corps, l’identité, les liens ou la compréhension du monde.",
     "Vulnérabilité, limites franchies, atmosphère, attentes sensorielles et rapport entre ce qui est montré et ce qui reste hors champ. La peur gagne en force lorsqu’elle touche quelque chose de précis pour le personnage.",
     "L’horreur peut être surnaturelle ou réaliste. Le body horror travaille la transformation corporelle ; le folk horror les croyances et communautés ; l’horreur cosmique l’impuissance face à l’incompréhensible."),
    ("Science-fiction", "Une hypothèse scientifique, technique ou sociale transforme les conditions de l’existence. Le récit explore ses conséquences sur les individus et les systèmes, sans devoir prédire l’avenir.",
     "Cohérence de l’hypothèse, effets de second ordre, tensions entre progrès et usages. La technologie devient narrative lorsqu’elle modifie un choix, une relation ou une possibilité d’action.",
     "La hard SF accorde une attention particulière à la plausibilité scientifique ; la SF sociale aux institutions ; le space opera à l’aventure à grande échelle. Dystopie et post-apocalypse désignent des cadres possibles, pas toute la SF."),
    ("Fantasy / merveilleux", "Le surnaturel appartient aux possibilités admises du monde raconté. Magie, créatures ou puissances peuvent façonner les conflits, les cultures et l’expérience quotidienne.",
     "Rapport entre pouvoir et limites, cultures vivantes, coût des capacités et conséquences humaines. Tout expliquer n’est pas obligatoire : la cohérence peut relever du mythe et de la sensation autant que de règles explicites.",
     "La fantasy épique élargit les enjeux ; l’urban fantasy installe le merveilleux dans un cadre urbain ; la dark fantasy croise l’horreur. À distinguer du fantastique fondé sur une incertitude face à l’inexplicable."),
    ("Fantastique", "Un événement inexplicable fissure un monde jusque-là perçu comme ordinaire. Dans l’usage littéraire français, l’hésitation entre explication rationnelle et surnaturelle peut constituer le cœur du récit.",
     "Perception incertaine, détails quotidiens déstabilisés, témoins contradictoires, conséquences intimes de l’intrusion. Le doute doit produire des choix et pas seulement retarder une réponse.",
     "Dans le merveilleux, le surnaturel est admis ; dans l’horreur, la peur domine la promesse émotionnelle. Ces catégories se croisent, et le mot anglais fantasy ne correspond pas exactement au français fantastique."),
    ("Aventure", "L’exploration, la quête ou le voyage font découvrir des lieux, des épreuves et des possibilités nouvelles. Le mouvement transforme la connaissance du monde et souvent celle du personnage.",
     "Objectif concret, obstacles variés, découverte, initiative et conséquences du parcours. Chaque étape gagne à changer la situation plutôt qu’à reproduire le même défi dans un nouveau décor.",
     "L’action privilégie la confrontation physique ; l’aventure la traversée et la découverte. Une quête peut être historique, spatiale, comique ou intime sans perdre cette dynamique."),
    ("Action", "Les conflits se résolvent ou se compliquent par des actes physiques : poursuite, combat, sauvetage, fuite. La lisibilité de l’objectif et de l’espace permet au public de comprendre le risque.",
     "Objectifs immédiats, contraintes matérielles, géographie claire, capacités et limites des protagonistes. Une séquence d’action doit changer les rapports de force et exprimer des décisions.",
     "Le spectacle seul ne définit pas une histoire. Un film de guerre, d’espionnage ou de super-héros peut utiliser l’action tout en donnant la priorité au drame ou au suspense."),
    ("Historique", "Une époque passée structure les possibilités, les contraintes et les représentations des personnages. Le passé n’est pas seulement un décor vestimentaire : il affecte ce qu’ils peuvent savoir et décider.",
     "Recherche documentaire, matérialité du quotidien, rapports sociaux, langage accessible sans faux archaïsme. Distinguer les faits attestés, les zones incertaines et les libertés fictionnelles.",
     "Le biographique se concentre sur une vie ; l’uchronie diverge volontairement de l’histoire ; le récit de guerre peut adopter des promesses très différentes, de l’aventure au témoignage traumatique."),
    ("Western", "La frontière, la loi et la violence organisent souvent les rapports entre individu et communauté. Territoire, propriété, déplacement et construction des mythes en sont des questions fécondes.",
     "Espaces qui contraignent les choix, autorité disputée, codes moraux en conflit, coût de la violence. Interroger les points de vue absents du mythe permet d’éviter de traiter une vision historique comme neutre.",
     "Le western peut être classique, révisionniste ou contemporain. Il ne se réduit pas aux chevaux et aux duels : ses conflits se transposent à d’autres cadres."),
    ("Initiatique / passage à l’âge adulte", "L’expérience modifie la place qu’un personnage croit occuper dans le monde. Grandir peut signifier gagner en autonomie, perdre une certitude ou choisir ses propres valeurs.",
     "Épreuves qui mettent les croyances en jeu, premières responsabilités, appartenance et séparation. La transformation se voit dans les décisions finales, pas uniquement dans une prise de conscience verbale.",
     "Ce motif traverse presque tous les genres. Un récit initiatique n’exige ni héros adolescent ni parcours victorieux ; il peut raconter une maturation tardive ou ambiguë."),
    ("Dystopie / post-apocalypse", "La dystopie examine un ordre social oppressif ; le post-apocalyptique explore la vie après une rupture majeure. L’une ne suppose pas nécessairement l’autre.",
     "Mécanismes concrets de pouvoir ou de survie, compromis quotidiens, accès aux ressources, mémoire du monde antérieur. Relier le système aux choix du protagoniste évite une simple exposition théorique.",
     "Ces cadres peuvent accueillir une romance, une enquête, une satire ou une aventure. Ils ne prescrivent ni une révolte organisée ni une fin pessimiste."),
]
